## Numpy

In [1]:
import numpy as np

In ‘n’ bit memory we can store 2 to the power 'n' decimals. So if our memory size is 2 then it can store 2^2 = 4 decimals.for example:<br> 
Decimals:    0,1 ,2 ,03 <br>
Binary:        00,01,10,11 <br>
When we write,
     x = 5<br>
it needs around 3 bit(101) space to represent. but in reality for python, this is going to take around 20 bytes. But in numpy we can control the size, in terms of bits.

In [2]:
#For example, if we want to create a number that takes only 8 bits. 
np.int8

numpy.int8

The main advantage is that, 
<ul>
    <li>It has built in very fast.</li>
    <li>Take advantage of CPU instructions for matrices and arrays</li>
    <li>It has a very efficient representations of numbers,right that are not the regular objects of python</li>
</ul>

## Basic Numpy Arrays 

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = np.array([0,.5,1,1.5,2])

In [9]:
#Differnet index elements together return a tuple 
x = a[0],a[1]
print(x)

(1, 2)


In [13]:
b[0],b[2],b[-1]

(0.0, 1.0, 2.0)

In [11]:
#Slicing is same as list
a[1:-1]

array([2, 3])

In [12]:
#Multiindexing: it returns the index values and that is an array. 
b[[0,2,-1]]

array([0., 1., 2.])

## Array types 

In [14]:
a

array([1, 2, 3, 4])

In [15]:
#Checking datatype
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [20]:
#Change the type of the data
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [27]:
c = np.array(['a','b','c'])
c.dtype

dtype('<U1')

'<U1' means max character = 1

In [28]:
c = np.array(['abcsd','b','cdf'])
c.dtype

dtype('<U5')

In [32]:
#Numpy stores number,date,booleans but not a regular individual objects 
d = np.array([{'a':1},5,'a'])
d.dtype

dtype('O')

## Dimensions and shapes 

In [33]:
#Making a 2D array
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [34]:
#(row,columns)
A.shape

(2, 3)

In [35]:
#Dimension
A.ndim

2

In [37]:
#Making 3D array
B = np.array([
    [
     [12,11,10],
     [9,8,7],
    ],
    [
     [6,5,4],
     [3,2,1],
    ]
])

In [40]:
B.shape

(2, 2, 3)

In [41]:
B.ndim

3

In [43]:
#total data
B.size

12

In [46]:
#If the shape isn't consistent, it'll just fall back to regular Python objects:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])
C.dtype

C:\Users\student\AppData\Local\Temp/ipykernel_6940/1778584142.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  C = np.array([


dtype('O')

In [48]:
print(C.shape, C.size)

(2,) 2


## Indexing and Slicing of Matrices

In [51]:
#Squre Matrix
A = np.array([
#    0 1 2   
    [1,2,3], #0
    [4,5,6], #1 
    [7,8,9]  #2
])

In [50]:
#It returns 2nd rows 
A[1]

array([4, 5, 6])

In [52]:
#Second row first element
A[1][0]

4

In [54]:
#We can also write 
A[1,0]

4

In [55]:
#Without comma it workings for rows 
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
#First is for row and 2nd is for column 
A[:,:2]
#Taking all rows and first 2 columns value

array([[1, 2],
       [4, 5],
       [7, 8]])

In [57]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
# Changing all values in 2nd rows 
A[1] = np.array([10,11,12])
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [61]:
#Adding same values in 3rd rows 
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [99, 99, 99]])

## Summary statistics

In [62]:
a = np.array([1,2,3,4])

In [63]:
#Find the summation
a.sum()

10

In [64]:
#Find the average
a.mean()

2.5

In [65]:
#Find the standard deviation 
a.std()

1.118033988749895

In [67]:
#Find the variance 
a.var()

1.25

In [68]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [71]:
A.sum(), A.mean(), A.std()

(45, 5.0, 2.581988897471611)

In [72]:
#Do the operation in column wise
A.sum(axis=0)

array([12, 15, 18])

In [73]:
#Do the operation in row wise
A.mean(axis=1)

array([2., 5., 8.])

In [74]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [75]:
A.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

## Broadcasting and Vectorized operations

In [78]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [80]:
a+10

array([10, 11, 12, 13])

In [81]:
a*10

array([ 0, 10, 20, 30])

This operation is kind of similar to list comprehension. In list comprehension we write:  

In [85]:
l = [0,1,2,3]

In [87]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [82]:
a

array([0, 1, 2, 3])

So it actually not modify the array, it just return new array

In [83]:
#if we want to modify the array then
a+=100
a

array([100, 101, 102, 103])

In [89]:
b = np.array([100,100,100,100])
a-b

array([0, 1, 2, 3])

We can create many arrays using other arithmetic operations like (*,+,/,-,%). But the shape of both arrays must be identical. 

In [90]:
#Another example
a/b

array([1.  , 1.01, 1.02, 1.03])

## Boolean arrays

In [94]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [95]:
a[[0,-1]]

array([0, 3])

In [97]:
#This is another way of selecting data
a[[True,False,False,True]]

array([0, 3])

In [98]:
#This is the power of boolean arrays 
a>=2

array([False, False,  True,  True])

In [99]:
#The advantage of this is just filtering 
a[a>=2]

array([2, 3])

In [100]:
a.mean()

1.5

In [101]:
a[a>a.mean()]

array([2, 3])

In [102]:
# '~' this is not sign
a[~(a>a.mean())]

array([0, 1])

In [103]:
a[(a==0)|(a==1)]

array([0, 1])

In [104]:
a[(a<=2)&(a%2==0)]

array([0, 2])

In [108]:
A = np.random.randint(100,size=(3,3))
A

array([[28, 48, 63],
       [ 5, 90, 98],
       [28, 56, 74]])

In [110]:
A[np.array([
    [True,False,True],
    [False,True,False],
    [True,False,True]
])]

array([28, 63, 90, 28, 74])

In [111]:
A>30

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [112]:
A[A>30]

array([48, 63, 90, 98, 56, 74])